name: ci
on: 
  workflow_dispatch:
    inputs:
      trigger-release-and-deploy:
        type: boolean
        description: force release and deploy from non standard branches
        default: false 
  push:
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install prerequisites and dependencies
        uses: ./.github/actions/install

      - name: Check formatting
        run: npm run prettier

      - name: Check types
        run: npm run typecheck

      - name: Check linting
        run: npm run lint

      - name: Execute tests
        run: npm run test

      - name: Execute build
        run: npm run build

      - name: test truthy
        if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.trigger-release-and-deploy == 'true' }}
        run: echo "is truthy"

  release-and-deploy:
    needs: ci-pipeline
    if: ${{ github.ref == 'refs/heads/main' || github.event.inputs.trigger-release-and-deploy == 'true' }}
    uses: ./.github/workflows/release-and-deploy.yaml
    permissions:
      pages: write
      id-token: write
