name: ci-cd-workflow
on: [workflow_dispatch, push]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run prettier

      - name: Check types
        run: npm run typecheck

      - name: Check linting
        run: npm run lint

      - name: Execute tests
        run: npm run test

      - name: Execute build
        run: npm run build

      - name: Upload dist as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  cd-pipeline:
    needs: ci-pipeline
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    outputs:
      pages-url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Output env url
        run: echo ${{ env.url }}

  smoke-test:
    runs-on: ubuntu-latest
    <TODO: add a requirement, to run the cd-pipeline first>
    <TODO: add a timeout for the job to 3 minutes>
    <TODO: add a matrix to execute the whole job for `firefox` and `chromium`>
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install <TODO: use one the value of the current matrix execution>

      - name: Run Playwright tests
        run: npx playwright test --project <TODO: use one the value of the current matrix execution>
        env:
          PLAYWRIGHT_BASE_URL: <TODO: use the pages-url as provided by the cd-pipeline>

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-<TODO: use one the value of the current matrix execution>
          path: playwright-report/
          retention-days: 1
