name: ci-workflow
on: [<TODO: should run whenever a push is performed>, <TODO: enable manual execution>]
jobs:
  ci-pipeline:
    <TODO: run the job on the GitHub provided ubuntu-latest runner>
    steps:
      - name: Check out repository
        uses: <TODO: use GitHub provided default actions>

      - name: Set up node 20
        uses: <TODO: use GitHub provided default actions>

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: <TODO: run the appropriate npm command>

      - name: Check types
        run: <TODO: run the appropriate npm command>

      - name: Check linting
        run: <TODO: run the appropriate npm command>

      - name: Execute tests
        run: <TODO: run the appropriate npm command>

      - name: Execute build
        run: <TODO: run the appropriate npm command>

      - name: Upload dist as artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'
