name: 'install'
description: 'installs node and all npm dependencies'
inputs:
  node-version:
    description: 'Node version'
    required: false
    default: '20'
runs:
  using: "composite"
  steps:
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}

    - name: Install dependencies
      run: npm ci
      shell: bash
    
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}