name: npm CICD pipeline

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push, workflow_dispatch]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      - name: check code format
        run: npm run prettier

      - name: check types
        run: npm run typecheck

      - name: run tests
        run: npm run test

      - name: build app
        run: npm run build

      - name: gh-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  cd-pipeline:
    runs-on: ubuntu-latest
    needs: ci-pipeline

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://alexstehli.github.io/gh-actions-workshop-example/

    steps:
      - name: deploy gh pages
        uses: actions/deploy-pages@v4
