name: Conditional Job Dependencies

on: [push]

jobs:
  B:
    runs-on: ubuntu-latest
    steps:
      - name: Run job B
        run: echo "Job B"

  C:
    runs-on: ubuntu-latest
    steps:
      - name: Run job C
        run: echo "Job C"

  A:
    runs-on: ubuntu-latest
    needs: [B, C]
    if: ${{ always() && (needs.B.result == 'success' || needs.C.result == 'success') }}
    steps:
      - name: Run job A
        run: echo "Job A"
