name: Conditional Job Workflow

on: [push]

jobs:
  Z:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check-output.outputs.result }}
    steps:
      - name: Determine output
        id: check-output
        run: |
          # Replace this with your actual logic to determine true or false
          echo "::set-output name=result::true"

  B:
    runs-on: ubuntu-latest
    needs: Z
    if: ${{ needs.Z.outputs.result == 'true' }}
    steps:
      - name: Run job B
        run: echo "Job B"

  C:
    runs-on: ubuntu-latest
    needs: Z
    if: ${{ needs.Z.outputs.result == 'false' }}
    steps:
      - name: Run job C
        run: echo "Job C"

  A:
    runs-on: ubuntu-latest
    needs: [B, C]
    if: ${{ always() && (needs.B.result == 'success' || needs.C.result == 'success') }}
    steps:
      - name: Run job A
        run: echo "Job A"
